# This is your Podfile - replace the post_install hook section

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/expo-modules-core/scripts/autolinking'

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'native' do
  use_expo_modules!
  config = use_native_modules!

  pod 'Firebase', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :fabric_enabled => false,
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :privacy_file_aggregation_enabled => false
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    # CRITICAL: Disable modular headers for ALL Firebase pods and React Native core
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        # Disable modular headers for all RNFB (React Native Firebase) pods
        if target.name.start_with?('RNFB')
          config.build_settings['USE_HEADERMAP'] = 'YES'
          config.build_settings['DEFINES_MODULE'] = 'NO'
          config.build_settings['CLANG_ENABLE_MODULES'] = 'NO'
        end
        
        # Disable modular headers for React Native core pods
        if ['React-Core', 'React-CoreModules', 'React-RCTNetwork', 'React-RCTText', 
            'React-RCTImage', 'React-RCTAnimation', 'React-RCTLinking', 'React-RCTSettings',
            'React-cxxreact', 'React-jsi', 'React-jsiexecutor', 'React-perflogger',
            'React-callinvoker', 'React-runtimeexecutor', 'React'].include?(target.name)
          config.build_settings['USE_HEADERMAP'] = 'YES'
          config.build_settings['DEFINES_MODULE'] = 'NO'
          config.build_settings['CLANG_ENABLE_MODULES'] = 'NO'
        end
      end
    end
  end
end
